#!/usr/bin/env bash

set -euo pipefail
shopt -s nullglob dotglob

mkdir -p "$HOME/.local/share/opencode" "$HOME/.config/opencode"

CONTAINER_CMD=$(if command -v podman >/dev/null 2>&1; then echo "podman"; else echo "docker"; fi)

exec "${CONTAINER_CMD}" run \
        --network=host \
        -v "${PWD}:${PWD}" \
        -v "${HOME}/.config/opencode:${HOME}/.config/opencode" \
        -v "${HOME}/.local/share/opencode:${HOME}/.local/share/opencode" \
        -v "${HOME}/.local/share/containers:${HOME}/.local/share/containers" \
        --cap-add SYS_ADMIN,MKNOD  \
        --device /dev/fuse \
        --security-opt label=disable \
        --user "$USER" \
        -e TERM \
        --userns=keep-id \
    --workdir "$PWD" \
    --rm -it localhost/opencode:latest \
    ~/bin/opencode "$@"
