#!/usr/bin/env bash

set -euo pipefail
shopt -s nullglob dotglob

mkdir -p "$HOME/.local/share/opencode" "$HOME/.config/opencode"

CONTAINER_CMD=$(if command -v podman >/dev/null 2>&1; then echo "podman"; else echo "docker"; fi)

exec "${CONTAINER_CMD}" run \
        -v "${PWD}:${PWD}" \
        -v "${HOME}/.config/opencode:/root/.config/opencode" \
        -v "${HOME}/.local/share/opencode:/root/.local/share/opencode" \
    --workdir "$PWD" \
    --rm -it opencode "$@"
