#!/usr/bin/env bash

set -euo pipefail
shopt -s nullglob dotglob

CONTAINER_CMD=$(if command -v podman >/dev/null 2>&1; then echo "podman"; else echo "docker"; fi)

exec "${CONTAINER_CMD}" exec -it -e TERM \
    ollama /usr/local/bin/ollama "$@"
