#!/usr/bin/env bash

set -euo pipefail
shopt -s nullglob dotglob

CONTAINER_CMD=$(if command -v podman >/dev/null 2>&1; then echo "podman"; else echo "docker"; fi)

mkdir -p "${HOME}/.ollama"

exec "${CONTAINER_CMD}" run --rm -d \
    --network=host \
    --device nvidia.com/gpu=all \
    --security-opt=label=disable \
    -v "${HOME}/.ollama:/root/.ollama" \
    --name ollama \
    \
    localhost/ollama:latest
