FROM registry.fedoraproject.org/fedora:43 as fedora_updated

ARG VERSION

# We want the latest versions.
# hadolint ignore=DL3041

RUN printf "\n\n# Added during image build\n" >> /etc/dnf/dnf.conf \
    && printf "minrate=100\ntimeout=60\nmax_parallel_downloads=8\nfastestmirror=True\n" >> /etc/dnf/dnf.conf \
    && printf "assumeyes=True\nkeepcache=1\nnodocs=True\ninstall_weak_deps=False\n" >> /etc/dnf/dnf.conf

RUN --mount=type=cache,dst=/var/cache/libdnf5/ --mount=type=tmpfs,dst=/var/log --mount=type=tmpfs,dst=/tmp --mount=type=tmpfs,dst=/var/tmp \
    dnf makecache \
    && dnf update \
    && curl -sL https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo -o /etc/yum.repos.d/nvidia-container-toolkit.repo \
    && dnf config-manager setopt nvidia-container-toolkit-experimental.enabled=1 \
    && dnf install libseccomp nvtop nnn nmap-ncat htop

RUN --mount=type=cache,dst=/var/cache/libdnf5/ --mount=type=tmpfs,dst=/var/log --mount=type=tmpfs,dst=/tmp --mount=type=tmpfs,dst=/var/tmp \
    dnf install --downloadonly nvidia-container-toolkit nvidia-container-toolkit-base libnvidia-container-tools libnvidia-container1 \
    && rpm -ihv --nodigest --nofiledigest /var/cache/libdnf*/nvidia-container-toolkit-*/packages/*.rpm \
    && curl -fsSL https://github.com/ollama/ollama/releases/download/v${VERSION}/ollama-linux-amd64.tgz | tar -xzv -C /usr/local

# This is to support AMD ROCM, 5.6 GiB / 8.6 GiB. Disabling to save space.
# RUN curl -fsSL https://ollama.com/download/ollama-linux-amd64-rocm.tgz | tar -xzv -C /usr/local

CMD /usr/local/bin/ollama serve
